"""
industries.py — Query config theo từng ngành.
Dùng trong main.py: INDUSTRY_QUERIES[industry]
"""

INDUSTRY_QUERIES = {
    "it": [
        "software company vietnam",
        "it outsourcing vietnam",
        "web development company vietnam",
        "mobile app development vietnam",
        "digital agency vietnam",
        "tech startup vietnam",
        "saas company vietnam",
        "ai company vietnam",
        "it service company ho chi minh",
        "software outsourcing hanoi",
        "outsourcing company vietnam",
        "software development firm vietnam",
        "app development company ho chi minh",
        "software house vietnam",
        "it consulting firm vietnam",
        "ecommerce development vietnam",
        "cloud services company vietnam",
        "blockchain company vietnam",
        "fintech company vietnam",
        "game development company vietnam",
        "cong ty phan mem viet nam",
        "cong ty cong nghe ho chi minh",
        "cong ty lap trinh ha noi",
        "startup cong nghe viet nam",
        "cong ty outsourcing viet nam",
    ],
    "manufacturing": [
        "manufacturing company vietnam",
        "factory vietnam ho chi minh",
        "production company vietnam",
        "industrial company vietnam",
        "garment factory vietnam",
        "electronics manufacturer vietnam",
        "furniture manufacturer vietnam",
        "plastic manufacturer vietnam",
        "food processing company vietnam",
        "packaging company vietnam",
        "steel company vietnam",
        "textile company vietnam",
        "cong ty san xuat viet nam",
        "cong ty che bien thuc pham",
        "nha may san xuat ha noi",
        "khu cong nghiep vietnam company",
        "manufacturing export vietnam",
        "oem manufacturer vietnam",
        "contract manufacturing vietnam",
        "industrial park company vietnam",
    ],
    "logistics": [
        "logistics company vietnam",
        "freight forwarding vietnam",
        "shipping company vietnam",
        "supply chain vietnam",
        "warehousing company vietnam",
        "3pl company vietnam",
        "express delivery vietnam",
        "cold chain logistics vietnam",
        "customs broker vietnam",
        "transport company ho chi minh",
        "cang bien viet nam company",
        "cong ty van tai viet nam",
        "cong ty logistics ha noi",
        "last mile delivery vietnam",
        "ecommerce logistics vietnam",
        "cross border logistics vietnam",
        "import export company vietnam",
        "forwarding agent vietnam",
        "trucking company vietnam",
        "air freight vietnam",
    ],
    "education": [
        "education company vietnam",
        "edtech startup vietnam",
        "english center vietnam",
        "training center ho chi minh",
        "online learning platform vietnam",
        "school management company vietnam",
        "tutoring center vietnam",
        "vocational training vietnam",
        "language school vietnam",
        "corporate training vietnam",
        "trung tam dao tao viet nam",
        "trung tam tieng anh ho chi minh",
        "cong ty giao duc viet nam",
        "e-learning company vietnam",
        "coding bootcamp vietnam",
        "education franchise vietnam",
        "preschool company vietnam",
        "k12 school vietnam",
        "university partnership vietnam",
        "skills training company vietnam",
    ],
    "healthcare": [
        "healthcare company vietnam",
        "clinic vietnam ho chi minh",
        "hospital vietnam private",
        "pharmaceutical company vietnam",
        "medical device company vietnam",
        "dental clinic vietnam",
        "health tech startup vietnam",
        "telemedicine vietnam",
        "wellness company vietnam",
        "beauty clinic vietnam",
        "cong ty duoc pham viet nam",
        "phong kham tu nhan ho chi minh",
        "cong ty y te viet nam",
        "mental health company vietnam",
        "fitness center vietnam",
        "spa wellness vietnam",
        "nutrition company vietnam",
        "biotech company vietnam",
        "lab diagnostic vietnam",
        "home care services vietnam",
    ],
    "retail": [
        "retail company vietnam",
        "ecommerce company vietnam",
        "fashion brand vietnam",
        "fmcg company vietnam",
        "supermarket chain vietnam",
        "convenience store vietnam",
        "online shop vietnam",
        "d2c brand vietnam",
        "consumer goods vietnam",
        "chuoi ban le viet nam",
        "thuong mai dien tu viet nam",
        "cong ty ban le ho chi minh",
        "grocery delivery vietnam",
        "fashion ecommerce vietnam",
        "beauty brand vietnam",
        "food delivery company vietnam",
        "marketplace vietnam",
        "b2c company vietnam",
        "retail tech vietnam",
        "omnichannel retail vietnam",
    ],
    "realestate": [
        "real estate company vietnam",
        "property developer vietnam",
        "construction company vietnam",
        "real estate agency vietnam",
        "proptech company vietnam",
        "housing developer vietnam",
        "commercial property vietnam",
        "resort developer vietnam",
        "cong ty bat dong san viet nam",
        "cong ty xay dung ho chi minh",
        "chu dau tu bat dong san",
        "property management vietnam",
        "co-working space vietnam",
        "serviced apartment vietnam",
        "interior design company vietnam",
        "architecture firm vietnam",
        "land developer vietnam",
        "condo developer vietnam",
        "smart home company vietnam",
        "facility management vietnam",
    ],
    "finance": [
        "fintech company vietnam",
        "investment company vietnam",
        "insurance company vietnam",
        "accounting firm vietnam",
        "financial consulting vietnam",
        "wealth management vietnam",
        "payment company vietnam",
        "lending startup vietnam",
        "cong ty tai chinh viet nam",
        "cong ty ke toan ho chi minh",
        "fund management vietnam",
        "venture capital vietnam",
        "private equity vietnam",
        "microfinance vietnam",
        "digital bank vietnam",
        "crypto company vietnam",
        "tax consulting vietnam",
        "audit firm vietnam",
        "financial technology vietnam",
        "money transfer vietnam",
    ],
    "hospitality": [
        "hotel company vietnam",
        "resort vietnam",
        "restaurant chain vietnam",
        "F&B company vietnam",
        "travel agency vietnam",
        "tourism company vietnam",
        "hospitality group vietnam",
        "catering company vietnam",
        "event management vietnam",
        "cong ty du lich viet nam",
        "chuoi nha hang viet nam",
        "khach san ho chi minh",
        "cong ty su kien ha noi",
        "wedding planner vietnam",
        "food company vietnam",
        "bakery chain vietnam",
        "coffee chain vietnam",
        "bar nightclub vietnam",
        "tour operator vietnam",
        "hotel management company vietnam",
    ],
}

# Danh sách ngành để validate
AVAILABLE_INDUSTRIES = list(INDUSTRY_QUERIES.keys())

# Pain points theo ngành — dùng trong AI prompt
INDUSTRY_PAIN_POINTS = {
    "it": "high employee turnover, remote team disconnection, developer burnout, poor team collaboration",
    "manufacturing": "worker retention, shift worker morale, safety culture, production line teamwork",
    "logistics": "driver and warehouse staff retention, high-stress environment, coordination between teams",
    "education": "teacher burnout, student engagement, staff collaboration, school culture building",
    "healthcare": "medical staff burnout, inter-department collaboration, patient care culture",
    "retail": "frontline staff turnover, seasonal workforce, customer service culture, team motivation",
    "realestate": "sales team motivation, agent retention, cross-team collaboration, competitive culture",
    "finance": "high-pressure environment, compliance culture, leadership alignment, talent retention",
    "hospitality": "seasonal staff, high turnover, service quality culture, team morale in peak seasons",
}
